format = """\
${username} ‚Ä∫ ${hostname} ${localip} ‚Ä∫ ${directory} ‚Ä∫ \
${git_branch}${git_commit}${git_state}${git_metrics}${git_status} ‚Ä∫ \
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$git_status\
$docker_context\
$aws\
$gcloud\
$openstack\
$azure\
$nats\
$direnv\
$env_var\
$mise\
$crystal\
$custom\
$sudo\
$cmd_duration\
$line_break\
$jobs\
$battery\
$time\
$status\
$os\
$container\
$netns\
$shell\

${memory_usage}\
${time}\
${directory}\
${git_branch}${git_commit}${git_state}${git_metrics}${git_status}\
${docker_context}\
${c}${cmake}${cobol}${daml}${dart}${deno}${dotnet}${elixir}${elm}${erlang}${fennel}${gleam}${golang}${guix_shell}${haskell}${haxe}${helm}${java}${julia}${kotlin}${gradle}${lua}${nim}${nodejs}${ocaml}${opa}${perl}${php}${pulumi}${purescript}${python}${quarto}${raku}${rlang}${red}${ruby}${rust}${scala}${solidity}${swift}${terraform}${typst}${vlang}${vagrant}${zig}\
${buf}${nix_shell}${conda}${meson}${spack}\
${package}\
${memory_usage}\
${aws}${gcloud}${openstack}${azure}\
${nats}\
${direnv}${env_var}\
${mise}\
${crystal}${custom}${sudo}\
${cmd_duration}${line_break}\
${jobs}\
${battery}${status}\
${os}\
${container}${netns}${shell}\
${character}"""

[[battery.display]]
  threshold = 20

[cmd_duration]
  format = '[${duration}](${style}) '

[directory]
  format = '[$path]($style)[$read_only]($read_only_style)'
  style = 'bold yellow'
  truncate_to_repo = false
  truncation_length = 8
  truncation_symbol = './'

[git_branch]
  always_show_remote = true
  format = '${symbol}[${branch}](${style})'
  style = 'blue'
  symbol = 'ÓÇ†'
  truncation_length = 20

[git_commit]
  format = ' [${hash}${tag}](${style})'
  style = 'bold blue'
  tag_disabled = false

[git_state]
  format = ' [${state}(${progress_current}/${progress_total})]($style)'
  style = 'bold blue'

[golang]
  format = '[${symbol}](${style})'
  version_format = '${raw}'

[hostname]
  format = '[${hostname}](${style})${ssh_symbol}'
  ssh_only = false
  ssh_symbol = 'üåê'
  style = 'blue'

[localip]
  disabled = false
  format = '[${localipv4}]($style)'
  ssh_only = false
  style = 'blue'

[nodejs]
  format = '[${symbol}](${style})'
  version_format = '${raw}'

[package]
  format = '[${symbol}${version}]($style) '
  symbol = 'üì¶'
  version_format = '${raw}'

[python]
  format = '[${symbol}](${style})'
  version_format = '${raw}'

[rust]
  format = '[${symbol}](${style})'
  version_format = '${raw}'

[time]
  disabled = false
  format = '[${time}](${style}) '
  style = 'bold blue'
  time_format = '%F %T'

[username]
  format = '[${user}](${style})'
  show_always = true
  style_root = 'yellow'
  style_user = 'yellow'
