format = """\
${username}${sudo} ‚Ä∫ ${hostname} ‚Ä∫ ${localip} ‚Ä∫ ${directory} \
${git_branch}${git_commit}${git_state}${git_status}${git_metrics}\
${container}${docker_context}${custom}\
${line_break}\
\
${character}"""

right_format = """\
${battery}${cmd_duration}${jobs}${memory_usage}${shlvl}${time}"""

[[battery.display]]
  threshold = 10

[cmd_duration]
  format = '( ‚Ä¶[${duration}](${style}) )'
  min_time = 5_0000
  style = 'white'

[directory]
  format = '[${path}](${style})[${read_only}](${read_only_style})'
  style = 'bold yellow'
  truncate_to_repo = false
  truncation_length = 8
  truncation_symbol = './'

[git_branch]
  always_show_remote = true
  format = '‚Ä∫ ${symbol}[${branch}](${style})'
  style = 'blue'
  symbol = 'ÓÇ†'
  truncation_length = 20

[git_commit]
  format = '[${hash}${tag}](${style})'
  style = 'bold blue'
  tag_disabled = false

[git_metrics]
  added_style = 'white'
  deleted_style = 'white'
  disabled = false
  format = '( (+${added})(${added_style})(-${deleted})(${deleted_style}))'
  ignore_submodules = true

[git_state]
  format = ' [${state}(${progress_current}/${progress_total})]($style)'
  style = 'bold blue'

[git_status]
  format = '( [${all_status}${ahead_behind}]($style))'
  style = 'white'

[golang]
  format = '[${symbol}](${style})'
  version_format = '${raw}'

[hostname]
  format = '[${hostname}](${style})( ${ssh_symbol})'
  ssh_only = false
  ssh_symbol = 'üåê'
  style = 'blue'

[localip]
  disabled = false
  format = '[${localipv4}]($style)'
  ssh_only = false
  style = 'blue'

[memory_usage]
  disabled = false
  format = '( [${ram}(|${swap})](${style}) )'
  style = 'bold red'
  symbol = 'üêè'
  threshold = 80

[nodejs]
  format = '[${symbol}](${style})'
  version_format = '${raw}'

[package]
  format = '[${symbol}${version}]($style) '
  symbol = 'üì¶'
  version_format = '${raw}'

[python]
  format = '[${symbol}](${style})'
  version_format = '${raw}'

[rust]
  format = '[${symbol}](${style})'
  version_format = '${raw}'

[shlvl]
  disabled = false
  format = '( [${symbol}${shlvl}]($style) )'
  repeat = true
  style = 'bold red'
  symbol = '‚ÜïÔ∏è'
  threshold = 3

[sudo]
  disabled = false
  format = '( [${symbol}]($style))'
  symbol = 'üßô'

[time]
  disabled = false
  format = '[${time}](${style})'
  style = 'dimmed white'
  time_format = '%F %T%Z'

[username]
  format = '[${user}](${style})'
  show_always = true
  style_root = 'yellow'
  style_user = 'yellow'
