format = """\
${username}${sudo} â€º ${hostname}${localip} â€º ${directory}\
${git_branch}${git_commit}${git_state}${git_status}${git_metrics}\
${container}${docker_context}${golang}${lua}${nodejs}${python}${rust}${package}\
${line_break}\
\
${character}"""

right_format = """\
${battery}${cmd_duration}${jobs}${memory_usage}${shlvl}${time}"""

[battery]
  charging_symbol = 'ó°‚„'
  discharging_symbol = 'ó°‚ƒ'
  empty_symbol = 'ó°‚'
  format = '( [${symbol}${percentage}](${style}) )'
  full_symbol = 'ó°¹'
  unknown_symbol = 'ó°½'

  [[battery.display]]
    style = 'bold red'
    threshold = 10

  [[battery.display]]
    style = 'bold yellow'
    threshold = 30

[cmd_duration]
  format = '( â€¦[${duration}](${style}) )'
  min_time = 10_000
  style = 'yellow'

[directory]
  format = '[${path}](${style})[${read_only}](${read_only_style})'
  style = 'bold yellow'
  truncate_to_repo = false
  truncation_length = 8
  truncation_symbol = './'

[git_branch]
  always_show_remote = true
  format = 'â€º ${symbol}[${branch}](${style})'
  style = 'blue'
  symbol = 'î‚ '
  truncation_length = 20

[git_commit]
  format = '[${hash}${tag}](${style})'
  style = 'bold blue'
  tag_disabled = false

[git_metrics]
  added_style = 'dimmed white'
  deleted_style = 'dimmed white'
  disabled = false
  format = '( (+${added})(${added_style})(-${deleted})(${deleted_style}))'
  ignore_submodules = true

[git_state]
  format = ' [${state}(${progress_current}/${progress_total})]($style)'
  style = 'bold blue'

[git_status]
  format = '( [${all_status}${ahead_behind}]($style))'
  style = 'dimmed white'

[golang]
  format = '( [${symbol}](${style}))'
  style = 'dimmed white'
  symbol = 'ğŸ¹'
  version_format = '${raw}'

[hostname]
  format = '[${hostname}](${style})( ${ssh_symbol})'
  ssh_only = false
  ssh_symbol = 'ğŸŒ'
  style = 'blue'

[jobs]
  disabled = false
  format = '( [${symbol}${number}](${style}) )'
  style = 'bold red'

[localip]
  disabled = false
  format = '( â€º [${localipv4}]($style))'
  ssh_only = true
  style = 'blue'

[lua]
  format = '( [${symbol}](${style}))'
  style = 'dimmed white'
  symbol = 'ğŸŒ™'
  version_format = '${raw}'

[memory_usage]
  disabled = false
  format = '( ${symbol}[${ram}(|${swap})](${style}) )'
  style = 'bold red'
  symbol = 'ğŸ'
  threshold = 80

[nodejs]
  format = '( [${symbol}](${style}))'
  style = 'dimmed white'
  symbol = 'îœ˜ '
  version_format = '${raw}'

[package]
  format = '( [${symbol}${version}](${style}))'
  style = 'dimmed white'
  symbol = 'ğŸ“¦'
  version_format = '${raw}'

[python]
  format = '( [${symbol}](${style}))'
  style = 'dimmed white'
  symbol = 'ğŸ'
  version_format = '${raw}'

[rust]
  format = '( [${symbol}](${style}))'
  style = 'dimmed white'
  symbol = 'ğŸ¦€'
  version_format = '${raw}'

[shlvl]
  disabled = false
  format = '( [${symbol}${shlvl}]($style) )'
  repeat = true
  style = 'bold red'
  symbol = 'â†•ï¸'
  threshold = 3

[sudo]
  disabled = false
  format = '( [${symbol}]($style))'
  symbol = 'ğŸ§™'

[time]
  disabled = false
  format = '[${time}](${style})'
  style = 'dimmed white'
  time_format = '%T, %F%Z'

[username]
  format = '[${user}](${style})'
  show_always = true
  style_root = 'yellow'
  style_user = 'yellow'
