services:
  tailscale:
    cap_add:
      - net_admin
    container_name: tailscale
    environment:
      - TS_AUTHKEY=file:${TS_AUTHKEY_FILE:?}
      - TS_EXTRA_ARGS=--accept-dns --accept-routes --force-reauth --login-server=${TS_LOGIN_SERVER:?} --reset
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
    hostname: DW-Swift
    image: tailscale/tailscale:latest
    network_mode: host
    restart: always
    volumes:
      - tailscale-state:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun

volumes:
  tailscale-state:
